# Generated by Django 5.2.1 on 2025-05-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('N_userProfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='graduation_year',
            field=models.CharField(max_length=10),
        ),
    ]
