# Generated by Django 5.2.1 on 2025-05-14 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('N_userProfile', '0002_alter_education_graduation_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certification',
            name='year',
            field=models.CharField(max_length=10),
        ),
    ]
