# Generated by Django 5.1.5 on 2025-07-22 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0002_remove_skill_job_joboffer_job_skill'),
        ('user', '0005_companyuser_support_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job.joboffer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.normaluser')),
            ],
        ),
    ]
