# Generated by Django 5.2.1 on 2025-07-23 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_joboffer_company'),
        ('savedJobs', '0001_initial'),
        ('user', '0005_companyuser_support_hours'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='savedjobs',
            unique_together={('user', 'job')},
        ),
    ]
