# Generated by Django 5.2.1 on 2025-05-15 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_profile', '0001_initial'),
        ('user', '0005_companyuser_support_hours'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employees',
            new_name='Employee',
        ),
    ]
