# Generated by Django 5.2.1 on 2025-05-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_education_user_remove_languages_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normaluser',
            name='video',
            field=models.URLField(null=True),
        ),
    ]
