# Generated by Django 5.2.1 on 2025-05-15 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_normaluser_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyuser',
            name='support_hours',
            field=models.CharField(default='Mon - Fri, 9am to 6pm', max_length=100),
        ),
    ]
