# Generated by Django 5.2.1 on 2025-07-12 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('job', '0002_remove_skill_job_joboffer_job_skill'),
        ('user', '0005_companyuser_support_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyAppliedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_letter', models.TextField()),
                ('salaryWithout', models.FloatField()),
                ('salaryWithFees', models.FloatField()),
                ('rate_increase', models.CharField(choices=[('3_months', '3_months'), ('6_months', '6_months'), ('every_year', 'every_year')], max_length=100)),
                ('increase_percentage', models.CharField(choices=[('5%', '5%'), ('10%', '10%'), ('15%', '15%')], max_length=10)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='job.joboffer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_jobs', to='user.normaluser')),
            ],
        ),
    ]
