# Generated by Django 5.1.5 on 2025-07-21 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appliedJobs', '0001_initial'),
        ('job', '0002_remove_skill_job_joboffer_job_skill'),
        ('user', '0005_companyuser_support_hours'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='myappliedjobs',
            unique_together={('user', 'job')},
        ),
    ]
