# Generated by Django 5.1.5 on 2025-07-22 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appliedJobs', '0002_alter_myappliedjobs_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='myappliedjobs',
            name='date',
            field=models.DateField(auto_now_add=True, default='2025-08-05'),
            preserve_default=False,
        ),
    ]
