# Generated by Django 5.2.1 on 2025-07-22 20:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_remove_skill_job_joboffer_job_skill'),
        ('user', '0005_companyuser_support_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.companyuser'),
        ),
    ]
