# Generated by Django 5.1.5 on 2025-07-24 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0003_joboffer_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='posted_at',
            field=models.DateField(auto_now_add=True, default='2025-8-5'),
            preserve_default=False,
        ),
    ]
